version: "3.0"
services:

  webapp:
    build: ./webapp
    image: vuln-webapp:1.0
    ports:
      - 80:80
    volumes:
      - ${PWD}/webapp/scweb:/var/www/web/scweb
    depends_on:
      - db

  db:
    # image: mysql
    build: ./db
    command: ['--default-authentication-plugin=mysql_native_password', '--secure-file-priv=/var/www/web/scweb']
    environment:
      MYSQL_ROOT_PASSWORD: user
      MYSQL_DATABASE: scdb
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 12
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
      - ${PWD}/webapp/scweb:/var/www/web/scweb
